// 模拟宠物数据（mock data），无需后端
const PETS = [
  {
    id: 1,
    name: "豆豆",
    type: "狗狗",
    breed: "柯基",
    age: 2,
    gender: "弟弟",
    price: 1200,
    location: "北京",
    vaccinated: true,
    neutered: true,
    character: ["活泼", "亲人", "爱运动"],
    desc: "豆豆是一只精力旺盛的小柯基，喜欢追球和散步，对小朋友非常友好，是家庭的开心果。",
    image: "🐶"
  },
  {
    id: 2,
    name: "咪咪",
    type: "猫咪",
    breed: "英短蓝猫",
    age: 1,
    gender: "妹妹",
    price: 1500,
    location: "上海",
    vaccinated: true,
    neutered: false,
    character: ["安静", "粘人", "温顺"],
    desc: "咪咪性格温和，喜欢窝在主人腿上睡觉，适合喜欢安静陪伴的铲屎官。",
    image: "🐱"
  },
  {
    id: 3,
    name: "球球",
    type: "兔子",
    breed: "垂耳兔",
    age: 1,
    gender: "弟弟",
    price: 300,
    location: "广州",
    vaccinated: false,
    neutered: false,
    character: ["胆小", "可爱", "安静"],
    desc: "球球是一只软萌的垂耳兔，爱吃青菜和胡萝卜，需要耐心温柔的主人。",
    image: "🐰"
  },
  {
    id: 4,
    name: "旺财",
    type: "狗狗",
    breed: "金毛",
    age: 3,
    gender: "弟弟",
    price: 2000,
    location: "深圳",
    vaccinated: true,
    neutered: true,
    character: ["聪明", "忠诚", "温顺"],
    desc: "旺财是标准的暖男金毛，聪明易训练，是导盲犬同款的靠谱伙伴。",
    image: "🐕"
  },
  {
    id: 5,
    name: "雪球",
    type: "猫咪",
    breed: "布偶猫",
    age: 2,
    gender: "妹妹",
    price: 3000,
    location: "杭州",
    vaccinated: true,
    neutered: true,
    character: ["优雅", "粘人", "安静"],
    desc: "雪球拥有一身蓬松的毛发和蓝眼睛，像小公主一样优雅，最爱被抱着。",
    image: "🐈"
  },
  {
    id: 6,
    name: "小绿",
    type: "乌龟",
    breed: "巴西龟",
    age: 5,
    gender: "未知",
    price: 80,
    location: "成都",
    vaccinated: false,
    neutered: false,
    character: ["慢热", "好养", "长寿"],
    desc: "小绿是超好养的巴西龟，不挑食、不闹腾，适合想养宠物又怕麻烦的你。",
    image: "🐢"
  },
  {
    id: 7,
    name: "花花",
    type: "狗狗",
    breed: "泰迪",
    age: 4,
    gender: "妹妹",
    price: 800,
    location: "武汉",
    vaccinated: true,
    neutered: true,
    character: ["机灵", "亲人", "小巧"],
    desc: "花花体型小巧不掉毛，聪明懂事，是公寓养狗的优选。",
    image: "🐩"
  },
  {
    id: 8,
    name: "橘座",
    type: "猫咪",
    breed: "橘猫",
    age: 2,
    gender: "弟弟",
    price: 600,
    location: "南京",
    vaccinated: true,
    neutered: false,
    character: ["能吃", "贪睡", "亲人"],
    desc: "橘座是传说中十橘九胖的代表，性格佛系，给吃就开心。",
    image: "🐈‍⬛"
  }
];
